language: python
python:
- '3.6'
install:
- python -m venv /home/travis/build/mikicz/travis-venv-test 
- python -m pip freeze
- /home/travis/build/mikicz/travis-venv-test/bin/python -m pip freeze
- /home/travis/build/mikicz/travis-venv-test/bin/python -m pip install arca
- python -m pip freeze
script:
- /home/travis/build/mikicz/travis-venv-test/bin/python -m pip freeze
notifications:
  email: false
